id: "services"
title: "Our AI Services"
content:
  title: "What we do"
  description: "Comprehensive artificial intelligence solutions tailored to your business needs"
  items:
    - title: "Customized AI Solutions"
      description: "Tailored systems that meet your unique business needs."
      icon: "check_circle"
      features:
        - "Custom machine learning models"
        - "AI strategy consulting"
        - "Integration with existing systems"
    
    - title: "Data-Driven Insights"
      description: "Advanced analytics to transform your data into actionable strategies."
      icon: "insights"
      features:
        - "Predictive analytics"
        - "Data visualization"
        - "Business intelligence"
    
    - title: "Intelligent Automation"
      description: "Streamlined, scalable workflows that grow with your business and reduce operational costs."
      icon: "speed"
      features:
        - "Process automation"
        - "Workflow optimization"
        - "Cost reduction strategies"
    
    - title: "B2B Outsourcing"
      description: "Comprehensive services that let you focus on core competencies while we handle specialized processes."
      icon: "business"
      link: "#b2b_outsourcing"
      features:
        - "Dedicated AI teams"
        - "Scalable solutions"
        - "24/7 support"

styling:
  theme: "light"
  layout: "full"
  customClasses: ""

metadata:
  order: 3
  visible: true
  lastUpdated: 2025-07-27T00:00:00.000Z
  author: "EvolverAI Team"
  
# Multi-language support
languages:
  it:
    title: "I nostri servizi IA"
    description: "Soluzioni complete di intelligenza artificiale personalizzate per le vostre esigenze aziendali"
    items:
      - title: "Soluzioni IA Personalizzate"
        description: "Sistemi su misura che soddisfano le vostre esigenze aziendali uniche."
      - title: "Insights Basati sui Dati"
        description: "Analisi avanzate per trasformare i vostri dati in strategie attuabili."
      - title: "Automazione Intelligente"
        description: "Flussi di lavoro semplificati e scalabili che crescono con la vostra azienda."
      - title: "Outsourcing B2B"
        description: "Servizi completi che vi permettono di concentrarvi sulle competenze principali."
  
  de:
    title: "Unsere KI-Dienste"
    description: "Umfassende KI-Lösungen, zugeschnitten auf Ihre Geschäftsanforderungen"
